name: "StrictDoc - End-to-end tests"

on:
  push:
    branches: [ "tdmg/**" ]

jobs:
  tests_end2end_macos:
    name: E2E - macOS
    runs-on: macos-13

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip

    - name: Install minimal Python packages
      run: |
        pip install -r requirements.bootstrap.txt

    - name: Run end-to-end tasks
      run: |
        tox -e py38-check -- pytest --failed-first --capture=no --reuse-session --exitfirst --strictdoc-long-timeouts -o cache_dir=build/pytest_end2end tests/end2end -k 'edit_grammar_move_field_down'
